// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client'
import { client } from './client.gen'
import type {
  CreateUserData,
  CreateUserErrors,
  CreateUserResponses,
  DeleteUserData,
  DeleteUserErrors,
  DeleteUserResponses,
  ForgotPasswordData,
  ForgotPasswordResponses,
  GetChatConversationsByIdData,
  GetChatConversationsByIdErrors,
  GetChatConversationsByIdResponses,
  GetChatConversationsGlobalData,
  GetChatConversationsGlobalErrors,
  GetChatConversationsGlobalResponses,
  GetChatMessagesByConversationIdData,
  GetChatMessagesByConversationIdErrors,
  GetChatMessagesByConversationIdResponses,
  GetCurrentUserData,
  GetCurrentUserErrors,
  GetCurrentUserResponses,
  GetMyReferralsData,
  GetMyReferralsResponses,
  GetUserData,
  GetUserErrors,
  GetUserResponses,
  ListUsersData,
  ListUsersResponses,
  LoginUserData,
  LoginUserErrors,
  LoginUserResponses,
  LogoutUserData,
  LogoutUserResponses,
  PostChatMessagesByConversationIdData,
  PostChatMessagesByConversationIdErrors,
  PostChatMessagesByConversationIdResponses,
  ResetPasswordData,
  ResetPasswordResponses,
  UpdateUserData,
  UpdateUserErrors,
  UpdateUserResponses,
  VerifyPasswordTokenData,
  VerifyPasswordTokenResponses,
} from './types.gen'

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>
}

/**
 * Autentica o usuário e define o cookie
 */
export const loginUser = <ThrowOnError extends boolean = false>(
  options: Options<LoginUserData, ThrowOnError>,
) =>
  (options.client ?? client).post<LoginUserResponses, LoginUserErrors, ThrowOnError>({
    responseType: 'json',
    url: '/auth/login',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Retorna o perfil do usuário logado
 */
export const getCurrentUser = <ThrowOnError extends boolean = false>(
  options?: Options<GetCurrentUserData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetCurrentUserResponses, GetCurrentUserErrors, ThrowOnError>({
    responseType: 'json',
    url: '/auth/me',
    ...options,
  })

/**
 * Remove o cookie de autenticação
 */
export const logoutUser = <ThrowOnError extends boolean = false>(
  options?: Options<LogoutUserData, ThrowOnError>,
) =>
  (options?.client ?? client).post<LogoutUserResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/auth/logout',
    ...options,
  })

/**
 * Solicita reset de senha
 */
export const forgotPassword = <ThrowOnError extends boolean = false>(
  options: Options<ForgotPasswordData, ThrowOnError>,
) =>
  (options.client ?? client).post<ForgotPasswordResponses, unknown, ThrowOnError>({
    url: '/auth/recover-password/forgot',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Verifica se o token de reset é válido
 */
export const verifyPasswordToken = <ThrowOnError extends boolean = false>(
  options: Options<VerifyPasswordTokenData, ThrowOnError>,
) =>
  (options.client ?? client).get<VerifyPasswordTokenResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/auth/recover-password/verify',
    ...options,
  })

/**
 * Define a nova senha usando o token
 */
export const resetPassword = <ThrowOnError extends boolean = false>(
  options: Options<ResetPasswordData, ThrowOnError>,
) =>
  (options.client ?? client).post<ResetPasswordResponses, unknown, ThrowOnError>({
    url: '/auth/recover-password/reset',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Obter canal global
 */
export const getChatConversationsGlobal = <ThrowOnError extends boolean = false>(
  options?: Options<GetChatConversationsGlobalData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetChatConversationsGlobalResponses,
    GetChatConversationsGlobalErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/chat/conversations/global',
    ...options,
  })

/**
 * Obter conversa por ID
 */
export const getChatConversationsById = <ThrowOnError extends boolean = false>(
  options: Options<GetChatConversationsByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetChatConversationsByIdResponses,
    GetChatConversationsByIdErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/chat/conversations/{id}',
    ...options,
  })

/**
 * Histórico de mensagens
 */
export const getChatMessagesByConversationId = <ThrowOnError extends boolean = false>(
  options: Options<GetChatMessagesByConversationIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetChatMessagesByConversationIdResponses,
    GetChatMessagesByConversationIdErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/chat/messages/{conversationId}',
    ...options,
  })

/**
 * Enviar mensagem
 */
export const postChatMessagesByConversationId = <ThrowOnError extends boolean = false>(
  options: Options<PostChatMessagesByConversationIdData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostChatMessagesByConversationIdResponses,
    PostChatMessagesByConversationIdErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/chat/messages/{conversationId}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Lista minhas indicações
 */
export const getMyReferrals = <ThrowOnError extends boolean = false>(
  options?: Options<GetMyReferralsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetMyReferralsResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/referrals/me',
    ...options,
  })

/**
 * Lista todos os usuários
 */
export const listUsers = <ThrowOnError extends boolean = false>(
  options?: Options<ListUsersData, ThrowOnError>,
) =>
  (options?.client ?? client).get<ListUsersResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/users/',
    ...options,
  })

/**
 * Cria um novo usuário
 */
export const createUser = <ThrowOnError extends boolean = false>(
  options: Options<CreateUserData, ThrowOnError>,
) =>
  (options.client ?? client).post<CreateUserResponses, CreateUserErrors, ThrowOnError>({
    responseType: 'json',
    url: '/users/',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Remove um usuário (Soft Delete)
 */
export const deleteUser = <ThrowOnError extends boolean = false>(
  options: Options<DeleteUserData, ThrowOnError>,
) =>
  (options.client ?? client).delete<DeleteUserResponses, DeleteUserErrors, ThrowOnError>({
    responseType: 'json',
    url: '/users/{id}',
    ...options,
  })

/**
 * Busca usuário por ID
 */
export const getUser = <ThrowOnError extends boolean = false>(
  options: Options<GetUserData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetUserResponses, GetUserErrors, ThrowOnError>({
    responseType: 'json',
    url: '/users/{id}',
    ...options,
  })

/**
 * Atualiza um usuário
 */
export const updateUser = <ThrowOnError extends boolean = false>(
  options: Options<UpdateUserData, ThrowOnError>,
) =>
  (options.client ?? client).put<UpdateUserResponses, UpdateUserErrors, ThrowOnError>({
    responseType: 'json',
    url: '/users/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
