// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseURL: 'http://localhost:3000' | (string & {})
}

export type LoginUserData = {
  body: {
    email: string
    password: string
  }
  path?: never
  query?: never
  url: '/auth/login'
}

export type LoginUserErrors = {
  /**
   * Default Response
   */
  401: {
    statusCode: number
    error: string
    message: string
    code?: string
    errors?: Array<{
      path: Array<string>
      message: string
    }>
  }
}

export type LoginUserError = LoginUserErrors[keyof LoginUserErrors]

export type LoginUserResponses = {
  /**
   * Default Response
   */
  200: {
    message: string
    user: {
      id: string
      username: string
      email: string
      avatarUrl: string | null
    }
  }
}

export type LoginUserResponse = LoginUserResponses[keyof LoginUserResponses]

export type GetCurrentUserData = {
  body?: never
  path?: never
  query?: never
  url: '/auth/me'
}

export type GetCurrentUserErrors = {
  /**
   * Default Response
   */
  404: {
    statusCode: number
    error: string
    message: string
    code?: string
    errors?: Array<{
      path: Array<string>
      message: string
    }>
  }
}

export type GetCurrentUserError = GetCurrentUserErrors[keyof GetCurrentUserErrors]

export type GetCurrentUserResponses = {
  /**
   * Default Response
   */
  200: {
    username: string
    name: string
    email: string
    race: 'saiyan' | 'namekian' | 'human' | 'frieza_race' | 'majin' | 'android'
    avatarUrl?: string
    id: string
    isVerified: boolean
    isVip: boolean
    acceptedTermsAt: string
    createdAt: string
    updatedAt: string
  }
}

export type GetCurrentUserResponse = GetCurrentUserResponses[keyof GetCurrentUserResponses]

export type LogoutUserData = {
  body?: never
  path?: never
  query?: never
  url: '/auth/logout'
}

export type LogoutUserResponses = {
  /**
   * Default Response
   */
  200: {
    statusCode: number
    error: string
    message: string
    code?: string
    errors?: Array<{
      path: Array<string>
      message: string
    }>
  }
}

export type LogoutUserResponse = LogoutUserResponses[keyof LogoutUserResponses]

export type ForgotPasswordData = {
  body: {
    email: string
  }
  path?: never
  query?: never
  url: '/auth/recover-password/forgot'
}

export type ForgotPasswordResponses = {
  /**
   * Default Response
   */
  200: unknown
}

export type VerifyPasswordTokenData = {
  body?: never
  path?: never
  query: {
    token: string
  }
  url: '/auth/recover-password/verify'
}

export type VerifyPasswordTokenResponses = {
  /**
   * Default Response
   */
  200: {
    valid: boolean
    message: string
  }
}

export type VerifyPasswordTokenResponse =
  VerifyPasswordTokenResponses[keyof VerifyPasswordTokenResponses]

export type ResetPasswordData = {
  body: {
    token: string
    password: string
  }
  path?: never
  query?: never
  url: '/auth/recover-password/reset'
}

export type ResetPasswordResponses = {
  /**
   * Default Response
   */
  200: unknown
}

export type GetChatConversationsGlobalData = {
  body?: never
  path?: never
  query?: never
  url: '/chat/conversations/global'
}

export type GetChatConversationsGlobalErrors = {
  /**
   * Default Response
   */
  404: {
    statusCode: number
    error: string
    message: string
    code?: string
    errors?: Array<{
      path: Array<string>
      message: string
    }>
  }
}

export type GetChatConversationsGlobalError =
  GetChatConversationsGlobalErrors[keyof GetChatConversationsGlobalErrors]

export type GetChatConversationsGlobalResponses = {
  /**
   * Default Response
   */
  200: {
    id: string
    slug: string | null
    name: string | null
    type: 'global' | 'private' | 'group'
    createdAt: string
    updatedAt: string
  }
}

export type GetChatConversationsGlobalResponse =
  GetChatConversationsGlobalResponses[keyof GetChatConversationsGlobalResponses]

export type GetChatConversationsByIdData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/chat/conversations/{id}'
}

export type GetChatConversationsByIdErrors = {
  /**
   * Default Response
   */
  404: {
    statusCode: number
    error: string
    message: string
    code?: string
    errors?: Array<{
      path: Array<string>
      message: string
    }>
  }
}

export type GetChatConversationsByIdError =
  GetChatConversationsByIdErrors[keyof GetChatConversationsByIdErrors]

export type GetChatConversationsByIdResponses = {
  /**
   * Default Response
   */
  200: {
    id: string
    slug: string | null
    name: string | null
    type: 'global' | 'private' | 'group'
    createdAt: string
    updatedAt: string
  }
}

export type GetChatConversationsByIdResponse =
  GetChatConversationsByIdResponses[keyof GetChatConversationsByIdResponses]

export type GetChatMessagesByConversationIdData = {
  body?: never
  path: {
    conversationId: string
  }
  query?: never
  url: '/chat/messages/{conversationId}'
}

export type GetChatMessagesByConversationIdErrors = {
  /**
   * Default Response
   */
  404: {
    statusCode: number
    error: string
    message: string
    code?: string
    errors?: Array<{
      path: Array<string>
      message: string
    }>
  }
}

export type GetChatMessagesByConversationIdError =
  GetChatMessagesByConversationIdErrors[keyof GetChatMessagesByConversationIdErrors]

export type GetChatMessagesByConversationIdResponses = {
  /**
   * Default Response
   */
  200: Array<{
    id: string
    conversationId: string
    senderId: string
    content: string
    type: 'text' | 'system'
    createdAt: string
    editedAt: string | null
    sender: {
      id: string
      username: string
      name: string
      avatarUrl: string | null
      isVerified: boolean
      race: 'saiyan' | 'namekian' | 'human' | 'frieza_race' | 'majin' | 'android'
    }
  }>
}

export type GetChatMessagesByConversationIdResponse =
  GetChatMessagesByConversationIdResponses[keyof GetChatMessagesByConversationIdResponses]

export type PostChatMessagesByConversationIdData = {
  body: {
    content: string
  }
  path: {
    conversationId: string
  }
  query?: never
  url: '/chat/messages/{conversationId}'
}

export type PostChatMessagesByConversationIdErrors = {
  /**
   * Default Response
   */
  404: {
    statusCode: number
    error: string
    message: string
    code?: string
    errors?: Array<{
      path: Array<string>
      message: string
    }>
  }
}

export type PostChatMessagesByConversationIdError =
  PostChatMessagesByConversationIdErrors[keyof PostChatMessagesByConversationIdErrors]

export type PostChatMessagesByConversationIdResponses = {
  /**
   * Default Response
   */
  201: {
    id: string
    conversationId: string
    senderId: string
    content: string
    type: 'text' | 'system'
    createdAt: string
    editedAt: string | null
    sender: {
      id: string
      username: string
      name: string
      avatarUrl: string | null
      isVerified: boolean
      race: 'saiyan' | 'namekian' | 'human' | 'frieza_race' | 'majin' | 'android'
    }
  }
}

export type PostChatMessagesByConversationIdResponse =
  PostChatMessagesByConversationIdResponses[keyof PostChatMessagesByConversationIdResponses]

export type GetMyReferralsData = {
  body?: never
  path?: never
  query?: never
  url: '/referrals/me'
}

export type GetMyReferralsResponses = {
  /**
   * Default Response
   */
  200: Array<{
    id: string
    status: 'pending' | 'completed' | 'rewarded'
    createdAt: string
    referredUser: {
      username: string
      avatarUrl: string | null
    }
  }>
}

export type GetMyReferralsResponse = GetMyReferralsResponses[keyof GetMyReferralsResponses]

export type ListUsersData = {
  body?: never
  path?: never
  query?: never
  url: '/users/'
}

export type ListUsersResponses = {
  /**
   * Default Response
   */
  200: Array<{
    username: string
    name: string
    email: string
    race: 'saiyan' | 'namekian' | 'human' | 'frieza_race' | 'majin' | 'android'
    avatarUrl?: string
    id: string
    isVerified: boolean
    isVip: boolean
    acceptedTermsAt: string
    createdAt: string
    updatedAt: string
  }>
}

export type ListUsersResponse = ListUsersResponses[keyof ListUsersResponses]

export type CreateUserData = {
  body: {
    username: string
    name: string
    email: string
    race: 'saiyan' | 'namekian' | 'human' | 'frieza_race' | 'majin' | 'android'
    avatarUrl?: string
    password: string
    acceptedTerms: true
  }
  path?: never
  query?: {
    ref?: string
  }
  url: '/users/'
}

export type CreateUserErrors = {
  /**
   * Default Response
   */
  400: {
    statusCode: number
    error: string
    message: string
    code?: string
    errors?: Array<{
      path: Array<string>
      message: string
    }>
  }
}

export type CreateUserError = CreateUserErrors[keyof CreateUserErrors]

export type CreateUserResponses = {
  /**
   * Default Response
   */
  201: {
    username: string
    name: string
    email: string
    race: 'saiyan' | 'namekian' | 'human' | 'frieza_race' | 'majin' | 'android'
    avatarUrl?: string
    id: string
    isVerified: boolean
    isVip: boolean
    acceptedTermsAt: string
    createdAt: string
    updatedAt: string
  }
}

export type CreateUserResponse = CreateUserResponses[keyof CreateUserResponses]

export type DeleteUserData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/users/{id}'
}

export type DeleteUserErrors = {
  /**
   * Default Response
   */
  404: {
    statusCode: number
    error: string
    message: string
    code?: string
    errors?: Array<{
      path: Array<string>
      message: string
    }>
  }
}

export type DeleteUserError = DeleteUserErrors[keyof DeleteUserErrors]

export type DeleteUserResponses = {
  /**
   * Usuário deletado com sucesso
   */
  204: null
}

export type DeleteUserResponse = DeleteUserResponses[keyof DeleteUserResponses]

export type GetUserData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/users/{id}'
}

export type GetUserErrors = {
  /**
   * Default Response
   */
  404: {
    statusCode: number
    error: string
    message: string
    code?: string
    errors?: Array<{
      path: Array<string>
      message: string
    }>
  }
}

export type GetUserError = GetUserErrors[keyof GetUserErrors]

export type GetUserResponses = {
  /**
   * Default Response
   */
  200: {
    username: string
    name: string
    email: string
    race: 'saiyan' | 'namekian' | 'human' | 'frieza_race' | 'majin' | 'android'
    avatarUrl?: string
    id: string
    isVerified: boolean
    isVip: boolean
    acceptedTermsAt: string
    createdAt: string
    updatedAt: string
  }
}

export type GetUserResponse = GetUserResponses[keyof GetUserResponses]

export type UpdateUserData = {
  body: {
    username?: string
    name?: string
    avatarUrl?: string
  }
  path: {
    id: string
  }
  query?: never
  url: '/users/{id}'
}

export type UpdateUserErrors = {
  /**
   * Default Response
   */
  404: {
    statusCode: number
    error: string
    message: string
    code?: string
    errors?: Array<{
      path: Array<string>
      message: string
    }>
  }
}

export type UpdateUserError = UpdateUserErrors[keyof UpdateUserErrors]

export type UpdateUserResponses = {
  /**
   * Default Response
   */
  200: {
    username: string
    name: string
    email: string
    race: 'saiyan' | 'namekian' | 'human' | 'frieza_race' | 'majin' | 'android'
    avatarUrl?: string
    id: string
    isVerified: boolean
    isVip: boolean
    acceptedTermsAt: string
    createdAt: string
    updatedAt: string
  }
}

export type UpdateUserResponse = UpdateUserResponses[keyof UpdateUserResponses]
