// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod'

export const zLoginUserData = z.object({
  body: z.object({
    email: z
      .string()
      .email()
      .regex(
        /^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$/,
      ),
    password: z.string().min(1).max(32),
  }),
  path: z.never().optional(),
  query: z.never().optional(),
})

/**
 * Default Response
 */
export const zLoginUserResponse = z.object({
  message: z.string(),
  user: z.object({
    id: z
      .string()
      .uuid()
      .regex(
        /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
      ),
    username: z.string(),
    email: z
      .string()
      .email()
      .regex(
        /^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$/,
      ),
    avatarUrl: z.union([z.string(), z.null()]),
  }),
})

export const zGetCurrentUserData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
})

/**
 * Default Response
 */
export const zGetCurrentUserResponse = z.object({
  username: z.string().min(3).max(32),
  name: z.string().min(2).max(32),
  email: z
    .string()
    .email()
    .regex(
      /^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$/,
    ),
  race: z.enum(['saiyan', 'namekian', 'human', 'frieza_race', 'majin', 'android']),
  avatarUrl: z.string().url().optional(),
  id: z
    .string()
    .uuid()
    .regex(
      /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
    ),
  isVerified: z.boolean(),
  isVip: z.boolean(),
  acceptedTermsAt: z.string().datetime(),
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
})

export const zLogoutUserData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
})

/**
 * Default Response
 */
export const zLogoutUserResponse = z.object({
  statusCode: z.number().int().gte(-9007199254740991).lte(9007199254740991),
  error: z.string(),
  message: z.string(),
  code: z.string().optional(),
  errors: z
    .array(
      z.object({
        path: z.array(z.string()),
        message: z.string(),
      }),
    )
    .optional(),
})

export const zForgotPasswordData = z.object({
  body: z.object({
    email: z
      .string()
      .email()
      .regex(
        /^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$/,
      ),
  }),
  path: z.never().optional(),
  query: z.never().optional(),
})

export const zVerifyPasswordTokenData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.object({
    token: z.string().min(1),
  }),
})

/**
 * Default Response
 */
export const zVerifyPasswordTokenResponse = z.object({
  valid: z.boolean(),
  message: z.string(),
})

export const zResetPasswordData = z.object({
  body: z.object({
    token: z.string().min(1),
    password: z.string().min(6).max(32),
  }),
  path: z.never().optional(),
  query: z.never().optional(),
})

export const zGetChatConversationsGlobalData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
})

/**
 * Default Response
 */
export const zGetChatConversationsGlobalResponse = z.object({
  id: z
    .string()
    .uuid()
    .regex(
      /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
    ),
  slug: z.union([z.string(), z.null()]),
  name: z.union([z.string(), z.null()]),
  type: z.enum(['global', 'private', 'group']),
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
})

export const zGetChatConversationsByIdData = z.object({
  body: z.never().optional(),
  path: z.object({
    id: z
      .string()
      .uuid()
      .regex(
        /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
      ),
  }),
  query: z.never().optional(),
})

/**
 * Default Response
 */
export const zGetChatConversationsByIdResponse = z.object({
  id: z
    .string()
    .uuid()
    .regex(
      /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
    ),
  slug: z.union([z.string(), z.null()]),
  name: z.union([z.string(), z.null()]),
  type: z.enum(['global', 'private', 'group']),
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
})

export const zGetChatMessagesByConversationIdData = z.object({
  body: z.never().optional(),
  path: z.object({
    conversationId: z
      .string()
      .uuid()
      .regex(
        /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
      ),
  }),
  query: z.never().optional(),
})

/**
 * Default Response
 */
export const zGetChatMessagesByConversationIdResponse = z.array(
  z.object({
    id: z
      .string()
      .uuid()
      .regex(
        /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
      ),
    conversationId: z
      .string()
      .uuid()
      .regex(
        /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
      ),
    senderId: z
      .string()
      .uuid()
      .regex(
        /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
      ),
    content: z.string(),
    type: z.enum(['text', 'system']),
    createdAt: z.string().datetime(),
    editedAt: z.union([z.string().datetime(), z.null()]),
    sender: z.object({
      id: z
        .string()
        .uuid()
        .regex(
          /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
        ),
      username: z.string(),
      name: z.string(),
      avatarUrl: z.union([z.string(), z.null()]),
      isVerified: z.boolean(),
      race: z.enum(['saiyan', 'namekian', 'human', 'frieza_race', 'majin', 'android']),
    }),
  }),
)

export const zPostChatMessagesByConversationIdData = z.object({
  body: z.object({
    content: z.string().min(1).max(1000),
  }),
  path: z.object({
    conversationId: z
      .string()
      .uuid()
      .regex(
        /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
      ),
  }),
  query: z.never().optional(),
})

/**
 * Default Response
 */
export const zPostChatMessagesByConversationIdResponse = z.object({
  id: z
    .string()
    .uuid()
    .regex(
      /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
    ),
  conversationId: z
    .string()
    .uuid()
    .regex(
      /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
    ),
  senderId: z
    .string()
    .uuid()
    .regex(
      /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
    ),
  content: z.string(),
  type: z.enum(['text', 'system']),
  createdAt: z.string().datetime(),
  editedAt: z.union([z.string().datetime(), z.null()]),
  sender: z.object({
    id: z
      .string()
      .uuid()
      .regex(
        /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
      ),
    username: z.string(),
    name: z.string(),
    avatarUrl: z.union([z.string(), z.null()]),
    isVerified: z.boolean(),
    race: z.enum(['saiyan', 'namekian', 'human', 'frieza_race', 'majin', 'android']),
  }),
})

export const zGetMyReferralsData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
})

/**
 * Default Response
 */
export const zGetMyReferralsResponse = z.array(
  z.object({
    id: z.string(),
    status: z.enum(['pending', 'completed', 'rewarded']),
    createdAt: z.string().datetime(),
    referredUser: z.object({
      username: z.string(),
      avatarUrl: z.union([z.string(), z.null()]),
    }),
  }),
)

export const zListUsersData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
})

/**
 * Default Response
 */
export const zListUsersResponse = z.array(
  z.object({
    username: z.string().min(3).max(32),
    name: z.string().min(2).max(32),
    email: z
      .string()
      .email()
      .regex(
        /^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$/,
      ),
    race: z.enum(['saiyan', 'namekian', 'human', 'frieza_race', 'majin', 'android']),
    avatarUrl: z.string().url().optional(),
    id: z
      .string()
      .uuid()
      .regex(
        /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
      ),
    isVerified: z.boolean(),
    isVip: z.boolean(),
    acceptedTermsAt: z.string().datetime(),
    createdAt: z.string().datetime(),
    updatedAt: z.string().datetime(),
  }),
)

export const zCreateUserData = z.object({
  body: z.object({
    username: z.string().min(3).max(32),
    name: z.string().min(2).max(32),
    email: z
      .string()
      .email()
      .regex(
        /^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$/,
      ),
    race: z.enum(['saiyan', 'namekian', 'human', 'frieza_race', 'majin', 'android']),
    avatarUrl: z.string().url().optional(),
    password: z.string().min(6),
    acceptedTerms: z.literal(true),
  }),
  path: z.never().optional(),
  query: z
    .object({
      ref: z.string().optional(),
    })
    .optional(),
})

/**
 * Default Response
 */
export const zCreateUserResponse = z.object({
  username: z.string().min(3).max(32),
  name: z.string().min(2).max(32),
  email: z
    .string()
    .email()
    .regex(
      /^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$/,
    ),
  race: z.enum(['saiyan', 'namekian', 'human', 'frieza_race', 'majin', 'android']),
  avatarUrl: z.string().url().optional(),
  id: z
    .string()
    .uuid()
    .regex(
      /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
    ),
  isVerified: z.boolean(),
  isVip: z.boolean(),
  acceptedTermsAt: z.string().datetime(),
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
})

export const zDeleteUserData = z.object({
  body: z.never().optional(),
  path: z.object({
    id: z
      .string()
      .uuid()
      .regex(
        /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
      ),
  }),
  query: z.never().optional(),
})

/**
 * Usuário deletado com sucesso
 */
export const zDeleteUserResponse = z.unknown()

export const zGetUserData = z.object({
  body: z.never().optional(),
  path: z.object({
    id: z
      .string()
      .uuid()
      .regex(
        /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
      ),
  }),
  query: z.never().optional(),
})

/**
 * Default Response
 */
export const zGetUserResponse = z.object({
  username: z.string().min(3).max(32),
  name: z.string().min(2).max(32),
  email: z
    .string()
    .email()
    .regex(
      /^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$/,
    ),
  race: z.enum(['saiyan', 'namekian', 'human', 'frieza_race', 'majin', 'android']),
  avatarUrl: z.string().url().optional(),
  id: z
    .string()
    .uuid()
    .regex(
      /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
    ),
  isVerified: z.boolean(),
  isVip: z.boolean(),
  acceptedTermsAt: z.string().datetime(),
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
})

export const zUpdateUserData = z.object({
  body: z.object({
    username: z.string().min(3).max(32).optional(),
    name: z.string().min(2).max(32).optional(),
    avatarUrl: z.string().url().optional(),
  }),
  path: z.object({
    id: z
      .string()
      .uuid()
      .regex(
        /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
      ),
  }),
  query: z.never().optional(),
})

/**
 * Default Response
 */
export const zUpdateUserResponse = z.object({
  username: z.string().min(3).max(32),
  name: z.string().min(2).max(32),
  email: z
    .string()
    .email()
    .regex(
      /^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$/,
    ),
  race: z.enum(['saiyan', 'namekian', 'human', 'frieza_race', 'majin', 'android']),
  avatarUrl: z.string().url().optional(),
  id: z
    .string()
    .uuid()
    .regex(
      /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
    ),
  isVerified: z.boolean(),
  isVip: z.boolean(),
  acceptedTermsAt: z.string().datetime(),
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
})
