// This file is auto-generated by @hey-api/openapi-ts

import { type _JSONValue, defineQueryOptions, type UseMutationOptions } from '@pinia/colada'
import type { AxiosError } from 'axios'

import { serializeQueryKeyValue } from '../client'
import { client } from '../client.gen'
import {
  createUser,
  deleteUser,
  forgotPassword,
  getChatConversationsById,
  getChatConversationsGlobal,
  getChatMessagesByConversationId,
  getCurrentUser,
  getMyReferrals,
  getUser,
  listUsers,
  loginUser,
  logoutUser,
  type Options,
  postChatMessagesByConversationId,
  resetPassword,
  updateUser,
  verifyPasswordToken,
} from '../sdk.gen'
import type {
  CreateUserData,
  CreateUserError,
  CreateUserResponse,
  DeleteUserData,
  DeleteUserError,
  DeleteUserResponse,
  ForgotPasswordData,
  GetChatConversationsByIdData,
  GetChatConversationsGlobalData,
  GetChatMessagesByConversationIdData,
  GetCurrentUserData,
  GetMyReferralsData,
  GetUserData,
  ListUsersData,
  LoginUserData,
  LoginUserError,
  LoginUserResponse,
  LogoutUserData,
  LogoutUserResponse,
  PostChatMessagesByConversationIdData,
  PostChatMessagesByConversationIdError,
  PostChatMessagesByConversationIdResponse,
  ResetPasswordData,
  UpdateUserData,
  UpdateUserError,
  UpdateUserResponse,
  VerifyPasswordTokenData,
} from '../types.gen'

/**
 * Autentica o usuário e define o cookie
 */
export const loginUserMutation = (
  options?: Partial<Options<LoginUserData>>,
): UseMutationOptions<LoginUserResponse, Options<LoginUserData>, AxiosError<LoginUserError>> => ({
  mutation: async (vars) => {
    const { data } = await loginUser({
      ...options,
      ...vars,
      throwOnError: true,
    })
    return data
  },
})

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, 'path'> & {
    _id: string
    baseURL?: _JSONValue
    body?: _JSONValue
    query?: _JSONValue
    tags?: _JSONValue
  },
]

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseURL: options?.baseURL || (options?.client ?? client).getConfig().baseURL,
  } as QueryKey<TOptions>[0]
  if (tags) {
    params.tags = tags as unknown as _JSONValue
  }
  if (options?.body !== undefined) {
    const normalizedBody = serializeQueryKeyValue(options.body)
    if (normalizedBody !== undefined) {
      params.body = normalizedBody
    }
  }
  if (options?.path) {
    params.path = options.path
  }
  if (options?.query !== undefined) {
    const normalizedQuery = serializeQueryKeyValue(options.query)
    if (normalizedQuery !== undefined) {
      params.query = normalizedQuery
    }
  }
  return [params]
}

export const getCurrentUserQueryKey = (options?: Options<GetCurrentUserData>) =>
  createQueryKey('getCurrentUser', options)

/**
 * Retorna o perfil do usuário logado
 */
export const getCurrentUserQuery = defineQueryOptions((options?: Options<GetCurrentUserData>) => ({
  key: getCurrentUserQueryKey(options),
  query: async (context) => {
    const { data } = await getCurrentUser({
      ...options,
      ...context,
      throwOnError: true,
    })
    return data
  },
}))

/**
 * Remove o cookie de autenticação
 */
export const logoutUserMutation = (
  options?: Partial<Options<LogoutUserData>>,
): UseMutationOptions<LogoutUserResponse, Options<LogoutUserData>, AxiosError<Error>> => ({
  mutation: async (vars) => {
    const { data } = await logoutUser({
      ...options,
      ...vars,
      throwOnError: true,
    })
    return data
  },
})

/**
 * Solicita reset de senha
 */
export const forgotPasswordMutation = (
  options?: Partial<Options<ForgotPasswordData>>,
): UseMutationOptions<unknown, Options<ForgotPasswordData>, AxiosError<Error>> => ({
  mutation: async (vars) => {
    const { data } = await forgotPassword({
      ...options,
      ...vars,
      throwOnError: true,
    })
    return data
  },
})

export const verifyPasswordTokenQueryKey = (options: Options<VerifyPasswordTokenData>) =>
  createQueryKey('verifyPasswordToken', options)

/**
 * Verifica se o token de reset é válido
 */
export const verifyPasswordTokenQuery = defineQueryOptions(
  (options: Options<VerifyPasswordTokenData>) => ({
    key: verifyPasswordTokenQueryKey(options),
    query: async (context) => {
      const { data } = await verifyPasswordToken({
        ...options,
        ...context,
        throwOnError: true,
      })
      return data
    },
  }),
)

/**
 * Define a nova senha usando o token
 */
export const resetPasswordMutation = (
  options?: Partial<Options<ResetPasswordData>>,
): UseMutationOptions<unknown, Options<ResetPasswordData>, AxiosError<Error>> => ({
  mutation: async (vars) => {
    const { data } = await resetPassword({
      ...options,
      ...vars,
      throwOnError: true,
    })
    return data
  },
})

export const getChatConversationsGlobalQueryKey = (
  options?: Options<GetChatConversationsGlobalData>,
) => createQueryKey('getChatConversationsGlobal', options)

/**
 * Obter canal global
 */
export const getChatConversationsGlobalQuery = defineQueryOptions(
  (options?: Options<GetChatConversationsGlobalData>) => ({
    key: getChatConversationsGlobalQueryKey(options),
    query: async (context) => {
      const { data } = await getChatConversationsGlobal({
        ...options,
        ...context,
        throwOnError: true,
      })
      return data
    },
  }),
)

export const getChatConversationsByIdQueryKey = (options: Options<GetChatConversationsByIdData>) =>
  createQueryKey('getChatConversationsById', options)

/**
 * Obter conversa por ID
 */
export const getChatConversationsByIdQuery = defineQueryOptions(
  (options: Options<GetChatConversationsByIdData>) => ({
    key: getChatConversationsByIdQueryKey(options),
    query: async (context) => {
      const { data } = await getChatConversationsById({
        ...options,
        ...context,
        throwOnError: true,
      })
      return data
    },
  }),
)

export const getChatMessagesByConversationIdQueryKey = (
  options: Options<GetChatMessagesByConversationIdData>,
) => createQueryKey('getChatMessagesByConversationId', options)

/**
 * Histórico de mensagens
 */
export const getChatMessagesByConversationIdQuery = defineQueryOptions(
  (options: Options<GetChatMessagesByConversationIdData>) => ({
    key: getChatMessagesByConversationIdQueryKey(options),
    query: async (context) => {
      const { data } = await getChatMessagesByConversationId({
        ...options,
        ...context,
        throwOnError: true,
      })
      return data
    },
  }),
)

/**
 * Enviar mensagem
 */
export const postChatMessagesByConversationIdMutation = (
  options?: Partial<Options<PostChatMessagesByConversationIdData>>,
): UseMutationOptions<
  PostChatMessagesByConversationIdResponse,
  Options<PostChatMessagesByConversationIdData>,
  AxiosError<PostChatMessagesByConversationIdError>
> => ({
  mutation: async (vars) => {
    const { data } = await postChatMessagesByConversationId({
      ...options,
      ...vars,
      throwOnError: true,
    })
    return data
  },
})

export const getMyReferralsQueryKey = (options?: Options<GetMyReferralsData>) =>
  createQueryKey('getMyReferrals', options)

/**
 * Lista minhas indicações
 */
export const getMyReferralsQuery = defineQueryOptions((options?: Options<GetMyReferralsData>) => ({
  key: getMyReferralsQueryKey(options),
  query: async (context) => {
    const { data } = await getMyReferrals({
      ...options,
      ...context,
      throwOnError: true,
    })
    return data
  },
}))

export const listUsersQueryKey = (options?: Options<ListUsersData>) =>
  createQueryKey('listUsers', options)

/**
 * Lista todos os usuários
 */
export const listUsersQuery = defineQueryOptions((options?: Options<ListUsersData>) => ({
  key: listUsersQueryKey(options),
  query: async (context) => {
    const { data } = await listUsers({
      ...options,
      ...context,
      throwOnError: true,
    })
    return data
  },
}))

/**
 * Cria um novo usuário
 */
export const createUserMutation = (
  options?: Partial<Options<CreateUserData>>,
): UseMutationOptions<
  CreateUserResponse,
  Options<CreateUserData>,
  AxiosError<CreateUserError>
> => ({
  mutation: async (vars) => {
    const { data } = await createUser({
      ...options,
      ...vars,
      throwOnError: true,
    })
    return data
  },
})

/**
 * Remove um usuário (Soft Delete)
 */
export const deleteUserMutation = (
  options?: Partial<Options<DeleteUserData>>,
): UseMutationOptions<
  DeleteUserResponse,
  Options<DeleteUserData>,
  AxiosError<DeleteUserError>
> => ({
  mutation: async (vars) => {
    const { data } = await deleteUser({
      ...options,
      ...vars,
      throwOnError: true,
    })
    return data
  },
})

export const getUserQueryKey = (options: Options<GetUserData>) => createQueryKey('getUser', options)

/**
 * Busca usuário por ID
 */
export const getUserQuery = defineQueryOptions((options: Options<GetUserData>) => ({
  key: getUserQueryKey(options),
  query: async (context) => {
    const { data } = await getUser({
      ...options,
      ...context,
      throwOnError: true,
    })
    return data
  },
}))

/**
 * Atualiza um usuário
 */
export const updateUserMutation = (
  options?: Partial<Options<UpdateUserData>>,
): UseMutationOptions<
  UpdateUserResponse,
  Options<UpdateUserData>,
  AxiosError<UpdateUserError>
> => ({
  mutation: async (vars) => {
    const { data } = await updateUser({
      ...options,
      ...vars,
      throwOnError: true,
    })
    return data
  },
})
